### ISSUE TITLE
Is check_vanilla_mc a test?

### ISSUE THREAD

**Issue by HaroldRKingsberg** [HaroldRKingsberg/MLMC#6]
Does it actually do something users will need, or does it exist to make sure our numbers are correct?

If the former, I'm cool with where it is. If the latter, we need to move it out of production code and into a test module

**Comment by mtran2011** [comment]
@petercwill , what do you think? I'm leaning to say this is more like an end-to-end test in comparing the value we get from MC and the analytic B-S value

**Comment by petercwill** [comment]
I think it's primarily a check on our numbers so it should be moved to the testing folder.

However, I think it needs to be reworked.  I'm not sure it's correct in it's current incarnation.

**Comment by HaroldRKingsberg** [comment]
Since we all think it's a test, let's move it.
