### ISSUE TITLE
Naive MC method correctness

### ISSUE THREAD

**Issue by HaroldRKingsberg** [HaroldRKingsberg/MLMC#8]
I've run the Naive MC method here two different ways at this point: once using the current geometric Brownian motion concept and once with the closed-form solution concept. In both cases, I ran them about a thousand times apiece, and found the analytic solution only seemed to come up within the confidence interval 7% of the time at best. Additionally, the standard deviation of those runs is several orders of magnitude greater than the target.

(The code I've been running has been in the option_edits branch.)

I believe @petercwill identified something similar in Issue #6. I'm calling it a night as I have work tomorrow. If anyone figures out what we're doing wrong, please respond ASAP, since we're behind schedule here.

**Comment by HaroldRKingsberg** [comment]
I think our confidence interval may be:

`\mu_{paths} + \frac{\sigma_{paths}}{\sqrt{n_{paths}}}Z`

But I'm going off StackOverflow here.

**Comment by HaroldRKingsberg** [comment]
I think our confidence interval may be:

$\mu_{paths} + \frac{\sigma_{paths}}{\sqrt{n_{paths}}}Z$

But I'm going off StackOverflow here.

**Comment by HaroldRKingsberg** [comment]
Specifically: https://quant.stackexchange.com/questions/17204/what-does-convergence-in-monte-carlo-simulation-mean

**Comment by mtran2011** [comment]
I found an error in the AnalyticEuropeanStockOptionSolver formula.
I'm revising it and pushing to minh_branch, then make a pull request.
@HaroldRKingsberg : please review this change I'm going to make now to AnalyticEuropeanStockOptionSolver and merge later if you're ok

**Comment by mtran2011** [comment]
I think we're good now with a small fix in AnalyticEuropeanStockOptionSolver and its tests. 

I'm now looking at NaiveMCOptionSolver to see why we get a std dev of 2.46 while our target is 0.1

**Comment by HaroldRKingsberg** [comment]
@mtran2011 I wrote the analytic solver essentially by copying what you'd written in tests/analytic.py, and tested it against numbers generated by analytic.py. If there's a bug in AnalyticEuropeanStockOptionSolver, the problem's also in your original code.

I'm nearly positive the two ways are equivalent, the difference being whether or not you distribute exp(-rT) or not. I do prefer things the way you've changed them to -- fewer calculations -- but I'm pretty sure this wasn't a bug.

**Comment by mtran2011** [comment]
Actually the analytic solver did pass the test before so the bug, if any, wasn't there. I'm still looking at why so many of our MC-based values fall outside the target range

**Comment by HaroldRKingsberg** [comment]
It's because we've been stupid about this whole thing. What we want to do is specify max length of the confidence interval and the confidence level. We then keep creating paths until the confidence interval from our paths is within the max length. The confidence interval from the paths is calculated as the standard deviation of the paths normalized by the square root of the number of paths, multiplied by the Z-value.

So yes, the overwhelming majority of the paths will end up outside that confidence interval. However, the chance that the population mean will fall outside the confidence interval (sample mean +/- confidence interval) goes to nil.

What's our level logic?

**Comment by HaroldRKingsberg** [comment]
I can write this easily enough when I get home tonight.

**Comment by mtran2011** [comment]
I was the wrong one to put the formula for npaths and nsteps in there. After I do some reading, the algorithm and stopping criteria is like you said Harold, which is: 
`
while (sample std dev of the sampled payoffs > target stdev):
    simulate a new path
    get a new payoff from this path, add it to collection of sampled payoffs
    update the std dev of the sampled payoffs
`

**Comment by HaroldRKingsberg** [comment]
This has been implemented as of commit fa5e2769b279abc30799de0c0c73cab8bd968930

It should be noted this is a really slow way of going about things: it's about 5 seconds to get a confidence interval of +/- 0.1 (95%), and about 25 to get a confidence level of 0.05. This came out to about 60,000 paths for the 0.1 interval, and 280,000 for the 0.05 interval.
